volumes:
  db_storage:
  n8n_storage:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: n8n-postgres
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    container_name: n8n-app
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_PROTOCOL=https
      - N8N_HOST=${N8N_HOST}
      # 1 Hop for Caddy Proxy, 1 for Cloudflare
      - N8N_PROXY_HOPS=2
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=true
      - WEBHOOK_URL=https://${N8N_HOST}
      # - N8N_METRICS=true
      # - N8N_METRICS_INCLUDE_DEFAULT_METRICS=true
      # - N8N_METRICS_INCLUDE_CACHE_METRICS=true
      # - N8N_METRICS_INCLUDE_MESSAGE_EVENT_BUS_METRICS=true
      # - N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL=true
      # - N8N_METRICS_INCLUDE_NODE_TYPE_LABEL=true
      # - N8N_METRICS_INCLUDE_CREDENTIAL_TYPE_LABEL=true
      # - N8N_METRICS_INCLUDE_API_ENDPOINTS=true
      # - N8N_METRICS_INCLUDE_API_PATH_LABEL=true
      # - N8N_METRICS_INCLUDE_API_METHOD_LABEL=true
      # - N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL=true
      # - N8N_METRICS_INCLUDE_QUEUE_METRICS=true
      # - N8N_METRICS_QUEUE_METRICS_INTERVAL=20
    dns:
      - ${DNS_SERVER}
    ports:
      - "${N8N_PORT}:5678"
    depends_on:
      postgres:
        condition: service_healthy

  # n8n-mcp (AI assistant for workflow development)
  n8n-mcp:
    container_name: n8n-mcp
    image: ghcr.io/czlonkowski/n8n-mcp:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - N8N_MODE=true
      - MCP_MODE=http
      - N8N_API_URL=http://n8n:5678
      - N8N_API_KEY=${N8N_API_KEY:-}
      - AUTH_TOKEN=${MCP_AUTH_TOKEN}
    ports:
      - "8042:3000"
    depends_on:
      n8n:
        condition: service_started

  # prometheus:
  #   image: prom/prometheus:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - prometheus_data:/prometheus
  #   ports:
  #     - "${PROMETHEUS_PORT}:9090"

  # grafana:
  #   image: grafana/grafana:latest
  #   restart: unless-stopped
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   ports:
  #     - "${GRAFANA_PORT}:3000"
